[package]
name = "y2025"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["cookies", "json"] }
cookie_store = "0.21"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
